Created Home page with search and cards
ProjectHub-edu/Web pull request #3
Opened 2023-02-21 13:09 UTC by MelenkoOleksandr

## Link
[PHW-41](https://project-hub.atlassian.net/browse/PHW-41)

## Short Description
Created Home page with all elemens

2023-02-21 16:10 UTC, medreres requested changes
I think, all of the components used from features folder should be imported from index.ts file, not from the folder folder or whatever

2023-02-21 16:10 UTC, medreres commented on src/features/projects/components/ProjectCard.tsx
> +        <Typography variant="h6">AvailableRoles</Typography>
perhaps should've been Available Roles

2023-02-22 07:49 UTC, MelenkoOleksandr commented on src/features/projects/components/ProjectCard.tsx
> +        <Typography variant="h6">AvailableRoles</Typography>
Created new component

2023-02-23 13:11 UTC, medreres approved these changes

2023-03-07 21:07 UTC, merged